config/routes.rb
Chipsahoy::Application.routes.draw do
  root "pages#home"

  get "/sports" => "pages#sports"
  get "/foods" => "pages#foods"
  get "/places" => "pages#places"

  post '/login' => 'pages#login'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
  class PagesController < ApplicationController


    def home
      @username = session[:username]
    end

    def sports
      @username = session[:username]
    end

    def foods
      @username = session[:username]
    end

    def places
      @username = session[:username]
    end

    def login
      @username = params[:name]
      session[:username] = @username
      render 'home'
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Chips Ahoy</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/cerulean/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Chips Ahoy", root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Sports", sports_url %></li>
        <li><%= link_to "Foods", foods_url %></li>
        <li><%= link_to "Places", places_url %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/pages/foods.html.erb
<h1 class="page-header">Hello <%= @username %></h1>

<h2>Foods</h2>

<ol>
  <li>Cookies</li>
  <li>Pizza</li>
  <li>Ice Cream</li>
  <li>Cookies</li>
  <li>Iced Team</li>
</ol>

app/views/pages/home.html.erb
<h1 class="page-header">Hello <%= @username %></h1>

<%= form_tag login_path do %>
  <%= text_field_tag :name %>
  <%= submit_tag "Login" %>
<% end %>

app/views/pages/places.html.erb
<h1 class="page-header">Hello <%= @username %></h1>

<h2>Places</h2>

<ol>
  <li>1871</li>
  <li>United Center</li>
  <li>Millenium Park</li>
  <li>Wrigley Field</li>
</ol>

app/views/pages/sports.html.erb
<h1 class="page-header">Hello <%= @username %></h1>

<h2>Sports</h2>

<ol>
  <li>Hockey</li>
  <li>Baseball</li>
  <li>Hockey</li>
  <li>Curling</li>
  <li>Football</li>
</ol>